// Default data for homepage sections when database is empty
// Uses Wood Pro specific assets

export const DEFAULT_HERO_SLIDES = [
    {
        id: 'default-hero-1',
        title: 'Artisanat du Bois de Qualité',
        description: 'Créations sur mesure en bois massif pour sublimer vos espaces',
        image_url: '/assets/images/michel-pro-wood/hero/IMG_8705.JPG',
        video_url: null,
        label: 'Découvrez nos réalisations',
    },
    {
        id: 'default-hero-2',
        title: 'Menuiserie d\'Excellence',
        description: 'Meubles et agencements personnalisés avec passion',
        image_url: '/assets/images/michel-pro-wood/hero/IMG_8728.JPG',
        video_url: null,
        label: 'Nos services',
    },
    {
        id: 'default-hero-3',
        title: 'Savoir-Faire Artisanal',
        description: 'Des créations uniques qui racontent votre histoire',
        image_url: '/assets/images/michel-pro-wood/hero/878ebad3-fa90-4a0b-b0d1-0054159bf4f4.jpg',
        video_url: null,
        label: 'Contactez-nous',
    },
];

export const DEFAULT_VIDEO_SLIDES = [
    {
        id: 'default-video-1',
        title: 'Notre Savoir-Faire',
        description: 'Découvrez notre atelier et nos techniques de menuiserie',
        video_url: '/assets/images/michel-pro-wood/video/video5839317998111824221.mp4',
        cta_text: 'En savoir plus',
        cta_link: '/a-propos',
    },
    {
        id: 'default-video-2',
        title: 'Nos Créations',
        description: 'Un aperçu de nos réalisations en bois massif',
        video_url: '/assets/images/michel-pro-wood/video/video5839317998111824222.mp4',
        cta_text: 'Voir nos réalisations',
        cta_link: '/realisations',
    },
];

export const DEFAULT_REALIZATIONS = [
    {
        id: 'default-real-1',
        title: 'Armoire Sur Mesure',
        slug: 'armoire-sur-mesure',
        category_id: null,
        description: 'Armoire en bois massif avec finitions soignées',
        cover_image_url: '/assets/images/michel-pro-wood/realisation/armoir .JPG',
        is_featured: true,
        is_active: true,
        wood_realization_categories: null,
    },
    {
        id: 'default-real-2',
        title: 'Canapé Salon Premium',
        slug: 'canape-salon-premium',
        category_id: null,
        description: 'Canapé de salon en bois noble avec coussins confortables',
        cover_image_url: '/assets/images/michel-pro-wood/realisation/canape salon prmium.JPG',
        is_featured: true,
        is_active: true,
        wood_realization_categories: null,
    },
    {
        id: 'default-real-3',
        title: 'Ensemble Salon',
        slug: 'ensemble-salon',
        category_id: null,
        description: 'Ensemble complet pour salon avec table et chaises',
        cover_image_url: '/assets/images/michel-pro-wood/realisation/canape salon.JPG',
        is_featured: true,
        is_active: true,
        wood_realization_categories: null,
    },
    {
        id: 'default-real-4',
        title: 'Chaises de Salon',
        slug: 'chaises-salon',
        category_id: null,
        description: 'Chaises élégantes en bois sculpté',
        cover_image_url: '/assets/images/michel-pro-wood/realisation/chaise salon.JPG',
        is_featured: true,
        is_active: true,
        wood_realization_categories: null,
    },
    {
        id: 'default-real-5',
        title: 'Lit Double',
        slug: 'lit-double',
        category_id: null,
        description: 'Lit double en bois massif avec tête de lit sculptée',
        cover_image_url: '/assets/images/michel-pro-wood/realisation/lit .JPG',
        is_featured: true,
        is_active: true,
        wood_realization_categories: null,
    },
    {
        id: 'default-real-6',
        title: 'Table à Manger',
        slug: 'table-a-manger',
        category_id: null,
        description: 'Table à manger avec chaises assorties',
        cover_image_url: '/assets/images/michel-pro-wood/realisation/table chaisse sale a manger.JPG',
        is_featured: true,
        is_active: true,
        wood_realization_categories: null,
    },
    {
        id: 'default-real-7',
        title: 'Table de Salon',
        slug: 'table-salon',
        category_id: null,
        description: 'Table basse de salon en bois noble',
        cover_image_url: '/assets/images/michel-pro-wood/realisation/table salon.JPG',
        is_featured: true,
        is_active: true,
        wood_realization_categories: null,
    },
];
